Codium/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from inventory_tracker import views
from inventory_tracker.views import inventory_download, inventory_json


urlpatterns = [
    path('admin/', admin.site.urls),
    path('<int:pk>/',views.InventoryDetailView.as_view(),name='detail'),
    path('inventory_tracker/',include('inventory_tracker.urls',namespace='inventory_tracker')),
    path('download-csv/', inventory_download, name='inventory_download'),
    path('json/', inventory_json, name='inventory_json')
]

inventory_tracker/urls.py
from inventory_tracker import views
from django.urls import path
app_name = 'inventory_tracker'

urlpatterns = [
    path('',views.InventoryListView.as_view(),name='list'),
    path('create/',views.InventoryCreateView.as_view(),name='create'),
    path('<int:pk>/',views.InventoryDetailView.as_view(),name='detail')
]

inventory_tracker/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic import ListView
# Create your models here.

class Inventory(models.Model):
    name= models.CharField(max_length=256)
    serial_number = models.CharField(max_length=256)
    price = models.IntegerField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('inventory_tracker:detail',kwargs={'pk':self.pk})

inventory_tracker/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,TemplateView,DetailView
from . import models
from django.http import HttpResponse,JsonResponse
import operator
from django.db.models import Q
from functools import reduce
import csv
from django.core import serializers
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'


class InventoryListView(ListView):
    context_object_name = 'inventory'
    model = models.Inventory

    def get_queryset(self):
        result = super(InventoryListView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(price__icontains=q) for q in query_list))
            )

        return result

class InventoryCreateView(CreateView):
    fields = ('name','serial_number','price')
    model = models.Inventory

def inventory_download(request):
    items = models.Inventory.objects.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition']='attachment; filename="inventory.csv"'
    writer = csv.writer(response, delimiter=',')
    writer.writerow(['name','serial_number','price'])

    for obj in items:
        writer.writerow([obj.name, obj.serial_number, obj.price])

    return response

def inventory_json(request):
    inventory_list = models.Inventory.objects.all()
    output = serializers.serialize('json', inventory_list, fields=('name', 'serial_number', 'price'))

    return JsonResponse(output,safe=False, content_type="application/json")

class InventoryDetailView(DetailView):
    context_object_name = 'inventory_detail'
    model = models.Inventory
    template_name = 'inventory_tracker/inventory_detail.html'

inventory_tracker/templates/inventory_tracker/inventory_detail.html
  <!DOCTYPE html>
<html>
<head>
    <title>Inventory List</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

    <div class="jumbotron">
    <h1>Welcome to the inventory detail page.</h1>
    <h2>Inventory detail:</h2>
    <p>Name:{{ inventory_detail.name }}</p>
    <p>Serial Number:{{ inventory_detail.serial_number }}</p>
    <p>Price:{{ inventory_detail.price }}</p>


    <a class="btn btn-primary" href="{% url 'inventory_tracker:list' %}">Go Back To the Inventory List Page</a>
    </div>

inventory_tracker/templates/inventory_tracker/inventory_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Inventory List</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<div class="container">
    <h1>
        Create Inventory
    </h1>

    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
    </form>
    </div>

inventory_tracker/templates/inventory_tracker/inventory_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Inventory List</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>


<div class="container">
 <form id="searchform" action="{% url 'inventory_tracker:list' %}" method="get" accept-charset="utf-8">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        <i class="fa fa-search"></i>
      </button>
      <input class="form-control mr-sm-4" id="searchbox" name="q" type="text" placeholder="Search">
    </form>

    <h1>Welcome to a list of all the inventory.</h1>

    <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Serial</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    {% for inventory in inventory %}
      <tr>
        <td>{{ inventory.name }}</td>
        <td>{{ inventory.serial_number }}</td>
        <td>{{ inventory.price }}</td>

      </tr>
    {% endfor %}
  </tbody>
</table>

<a class="btn btn-primary" href="{% url 'inventory_tracker:create' %}">Create new inventory</a>

</div>
</body>
</html>